-- wms_atributos_base
CREATE TABLE IF NOT EXISTS public.wms_atributos_base (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    empresa_id BIGINT NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- wms_atributos_valores_base
CREATE TABLE IF NOT EXISTS public.wms_atributos_valores_base (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    atributo_id BIGINT NOT NULL REFERENCES public.wms_atributos_base(id) ON DELETE CASCADE,
    valor TEXT NOT NULL,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS
ALTER TABLE public.wms_atributos_base ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wms_atributos_valores_base ENABLE ROW LEVEL SECURITY;

-- Políticas
CREATE POLICY "Permitir select atributos base por empresa" ON public.wms_atributos_base 
FOR SELECT USING (auth.uid() IN (SELECT id FROM public.usuarios WHERE id = empresa_id));

CREATE POLICY "Permitir insert atributos base por empresa" ON public.wms_atributos_base
FOR INSERT WITH CHECK (auth.uid() IN (SELECT id FROM public.usuarios WHERE id = empresa_id));

CREATE POLICY "Permitir select valores base por empresa" ON public.wms_atributos_valores_base
FOR SELECT USING (
  atributo_id IN (SELECT id FROM public.wms_atributos_base WHERE empresa_id IN (SELECT id FROM public.usuarios WHERE id = auth.uid()))
);

CREATE POLICY "Permitir insert valores base por empresa" ON public.wms_atributos_valores_base
FOR INSERT WITH CHECK (
  atributo_id IN (SELECT id FROM public.wms_atributos_base WHERE empresa_id IN (SELECT id FROM public.usuarios WHERE id = auth.uid()))
);
